api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "pos-block"
uid = "a0a6f108-465b-a7bb-a503-81f2febf1a403793616f"
handle = "pos-block"
description = "A preact POS UI extension"

# module: path to the file that contains your extensionâ€™s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.product-details.action.render"

[[extensions.targeting]]
module = "./src/Block.jsx"
target = "pos.product-details.block.render"
